package main

import (
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

func main() {
	out := flag.String("out", ".", "directory to write generated files into")
	flag.Parse()
	emit(filepath.Join(*out, "iter_gen.go"), "ecs", "import \"unsafe\"", iterFamily(iterTmpl, 6))
	emit(filepath.Join(*out, "change_gen.go"), "ecs", "import \"unsafe\"", iterFamily(changedTmpl, 6))
	emit(filepath.Join(*out, "parallel_gen.go"), "ecs", "import (\n\t\"sync\"\n\t\"unsafe\"\n)", iterFamily(parallelTmpl, 4))
}

func emit(path, pkg, imports, body string) {
	src := fmt.Sprintf("// Code generated by ./internal/gen_iter; DO NOT EDIT.\n\npackage %s\n\n%s\n\n%s", pkg, imports, body)
	formatted, err := format.Source([]byte(src))
	if err != nil {
		fmt.Fprintln(os.Stderr, src)
		log.Fatalf("%s: %v", path, err)
	}
	if err := os.WriteFile(path, formatted, 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("wrote", path)
}

func iterFamily(tmpl string, max int) string {
	t := template.Must(template.New("iter").Funcs(template.FuncMap{
		"lower": strings.ToLower,
		"join":  func(s []string, sep string) string { return strings.Join(s, sep) },
		"prefixed": func(s []string, suffix string) []string {
			out := make([]string, len(s))
			for i, x := range s {
				out[i] = strings.ToLower(x) + suffix
			}
			return out
		},
	}).Parse(tmpl))
	var sb strings.Builder
	letters := []string{"A", "B", "C", "D", "E", "F"}
	for n := 1; n <= max; n++ {
		data := map[string]any{
			"N":       n,
			"Letters": letters[:n],
		}
		if err := t.Execute(&sb, data); err != nil {
			log.Fatal(err)
		}
	}
	return sb.String()
}

const iterTmpl = `
func Iter{{.N}}[{{join .Letters ", "}} any](world *World, extraInclude, exclude Mask, callback func(entity Entity{{range .Letters}}, {{. | lower}} *{{.}}{{end}})) {
	world.enterIter()
	defer world.leaveIter()
{{range .Letters}}	{{. | lower}}Info := mustComponentInfo[{{.}}](world)
{{end}}	include := extraInclude{{range .Letters}} | {{. | lower}}Info.mask{{end}}
	for _, tableIndex := range world.cachedTables(include) {
		table := world.tables[tableIndex]
		if table.Mask&exclude != 0 {
			continue
		}
		count := len(table.Entities)
		if count == 0 {
			continue
		}
{{range .Letters}}		{{. | lower}}Slice := unsafe.Slice((*{{.}})(table.columns[{{. | lower}}Info.bitIndex].dataPtr), count)
{{end}}		for arrayIndex := 0; arrayIndex < count; arrayIndex++ {
			callback(table.Entities[arrayIndex]{{range .Letters}}, &{{. | lower}}Slice[arrayIndex]{{end}})
		}
	}
}

`

const changedTmpl = `
func IterChanged{{.N}}[{{join .Letters ", "}} any](world *World, extraInclude, exclude Mask, callback func(entity Entity{{range .Letters}}, {{. | lower}} *{{.}}{{end}})) {
	world.enterIter()
	defer world.leaveIter()
{{range .Letters}}	{{. | lower}}Info := mustComponentInfo[{{.}}](world)
{{end}}	since := world.lastTick
	include := extraInclude{{range .Letters}} | {{. | lower}}Info.mask{{end}}
	for _, tableIndex := range world.cachedTables(include) {
		table := world.tables[tableIndex]
		if table.Mask&exclude != 0 {
			continue
		}
		count := len(table.Entities)
		if count == 0 {
			continue
		}
{{range .Letters}}		{{. | lower}}Column := table.columns[{{. | lower}}Info.bitIndex]
{{end}}{{range .Letters}}		{{. | lower}}Slice := unsafe.Slice((*{{.}})({{. | lower}}Column.dataPtr), count)
{{end}}		for arrayIndex := 0; arrayIndex < count; arrayIndex++ {
			if {{range $i, $L := .Letters}}{{if $i}} || {{end}}{{$L | lower}}Column.changed[arrayIndex] > since{{end}} {
				callback(table.Entities[arrayIndex]{{range .Letters}}, &{{. | lower}}Slice[arrayIndex]{{end}})
			}
		}
	}
}

`

const parallelTmpl = `
func ParallelIter{{.N}}[{{join .Letters ", "}} any](world *World, extraInclude, exclude Mask, callback func(entity Entity{{range .Letters}}, {{. | lower}} *{{.}}{{end}})) {
{{range .Letters}}	{{. | lower}}Info := mustComponentInfo[{{.}}](world)
{{end}}	include := extraInclude{{range .Letters}} | {{. | lower}}Info.mask{{end}}
	var wg sync.WaitGroup
	for _, tableIndex := range world.cachedTables(include) {
		table := world.tables[tableIndex]
		if table.Mask&exclude != 0 {
			continue
		}
		count := len(table.Entities)
		if count == 0 {
			continue
		}
{{range .Letters}}		{{. | lower}}Column := table.columns[{{. | lower}}Info.bitIndex]
{{end}}		wg.Add(1)
		go func(table *Archetype{{range .Letters}}, {{. | lower}}Column *column{{end}}, count int) {
			defer wg.Done()
{{range .Letters}}			{{. | lower}}Slice := unsafe.Slice((*{{.}})({{. | lower}}Column.dataPtr), count)
{{end}}			for arrayIndex := 0; arrayIndex < count; arrayIndex++ {
				callback(table.Entities[arrayIndex]{{range .Letters}}, &{{. | lower}}Slice[arrayIndex]{{end}})
			}
		}(table{{range .Letters}}, {{. | lower}}Column{{end}}, count)
	}
	wg.Wait()
}

`
